# Generated by Django 4.2.19 on 2025-03-04 21:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_userprofile_options_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('vacancy', 'user')},
        ),
    ]
