# Generated by Django 4.2.19 on 2025-03-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='vacancies', to='core.tag'),
        ),
    ]
