# Generated by Django 4.2.19 on 2025-04-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_resume_skill_workexperience_resume_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, help_text='Перечислите ваши навыки через запятую', verbose_name='Ключевые навыки'),
        ),
    ]
