# Generated by Django 4.2.19 on 2025-04-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_emailverificationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationcode',
            options={},
        ),
        migrations.RemoveField(
            model_name='emailverificationcode',
            name='user',
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
