# Generated by Django 4.2.19 on 2025-05-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_emailverificationcode_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='education',
            field=models.CharField(choices=[('none', 'Не требуется'), ('secondary', 'Среднее профессиональное'), ('higher', 'Высшее')], default='none', max_length=20, verbose_name='Требуемое образование'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('full', 'Полная занятость'), ('part', 'Частичная занятость'), ('project', 'Проектная работа/разовое задание'), ('volunteer', 'Волонтерство')], default='full', max_length=20, verbose_name='Тип занятости'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(choices=[('no_experience', 'Нет опыта'), ('1_3', 'От 1 года до 3 лет'), ('3_6', 'От 3 до 6 лет'), ('6_plus', 'Более 6 лет'), ('any', 'Не имеет значения')], default='any', max_length=20, verbose_name='Требуемый опыт'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='general_info',
            field=models.TextField(default='Общая информация о вакансии', verbose_name='Общая информация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='ideal_candidate',
            field=models.TextField(default='Наш идеальный кандидат', verbose_name='Наш идеальный кандидат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(default='Обязанности', verbose_name='Чем предстоит заниматься'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(default='Навыки', verbose_name='Требуемые навыки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='we_offer',
            field=models.TextField(default='Мы предлагаем', verbose_name='Что мы предлагаем'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Сброс пароля'), ('email_verification', 'Подтверждение email')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profession',
            field=models.CharField(help_text='Можно ввести несколько разных', max_length=100, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='Заработная плата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название вакансии'),
        ),
    ]
